# Generated by Django 4.2.11 on 2024-06-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='catégorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='travailleur',
            old_name='compétences',
            new_name='competences',
        ),
        migrations.RenameField(
            model_name='travailleur',
            old_name='expériences',
            new_name='experiences',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='prénom',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='rôle',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='téléphone',
            new_name='telephone',
        ),
    ]
